### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mcferdev** [tiger4589/Xamarin.Forms-CardView#1]
When trying to use the CardView tag on XAML, is not finding it. Has to do something more than install ?

**Comment by tiger4589** [comment]
After installing the package it should work easily. 
Note that you need to declare the namespace in the XAML header.
Please refer to <a href="https://github.com/tiger4589/Xamarin.Forms-CardView/blob/master/CardViewExamples/CardViewExample/CardViewExample/CardViewHasShadowPage.xaml">this example</a> and note the: 
`xmlns:cardView="clr-namespace:CardView;assembly=CardView"` inside the `ContentPage` tag.
Then you can use it like this:
`<cardView:CardView></cardView:CardView>`
Try it please and tell me what happens, and if you can share your sample project to see it it would be great :)

**Comment by tiger4589** [comment]
@marcelinhovt Have you been able to fix this?

**Comment by mcferdev** [comment]
Hello. Yes, fixed ! But was not what i need. In Android I cannot see the
shadow like iOS.
But thank you ! Its very nice and usefull.
In another moment, sure that I will use.

Regards.

2017-03-26 15:00 GMT-03:00 Paul Karam <notifications@github.com>:

**Comment by tiger4589** [comment]
I am glad you liked it. 
In Android it is by default just a little shadow I am afraid, I will try to make this much better when I get more time, in case you have any suggestions please post them here, I will close the issue now.
