### ISSUE TITLE
Not compatible with .NET Standard 2.0

### ISSUE THREAD

**Issue by DiogoTheCoder** [tiger4589/Xamarin.Forms-CardView#6]
Getting the an error message when I try out the example XAML code.

<CardView> <CardView.CardViewContent> <StackLayout> <Label Text="Label inside StackLayout forming the CardViewContent"></Label> </StackLayout> </CardView.CardViewContent> </CardView>

Type CardView not found in xmlns http://xamarin.com/schemas/2014/forms

I believe this error is being caused by the incompatibility, since Visual Studio is having to revert the package to the .NET Framework, instead of using .NET Standard

**Comment by tiger4589** [comment]
Hello @DiogoCosta1998 . Can you please create a new empty project exactly like the one you got an error while using CardView and upload it so I check it?

**Comment by DiogoCosta-Brunel** [comment]
[Output.txt](https://github.com/tiger4589/Xamarin.Forms-CardView/files/1571682/Output.txt)
[CardViewApp.zip](https://github.com/tiger4589/Xamarin.Forms-CardView/files/1571683/CardViewApp.zip)

**Comment by DiogoTheCoder** [comment]
[CardViewApp.zip](https://github.com/tiger4589/Xamarin.Forms-CardView/files/1571687/CardViewApp.zip)
[Output.txt](https://github.com/tiger4589/Xamarin.Forms-CardView/files/1571689/Output.txt)

**Comment by kenancasey** [comment]
Any update on this? I'd love to use this in .NET Standard 2.0.

**Comment by tiger4589** [comment]
I have just pushed a new package to Nuget that uses .Net Standard 2.0. to install: Install-Package XamarinForms.CardView.NetStandard
It might take up to an hour to get published, so if you can't directly install it give it up to an hour after the time of this post. Please give me your feedback if any error happened when trying it with .Net Standard.
